version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    tty: true
    environment:
      POSTGRES_PASSWORD: sunda
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 12027:12027
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3002:3002
    volumes:
      - .:/home/node/app